version: "3.9"
services:

  swapi_service:
    build: .
    env_file:
      - .env
    command:
      sh -c "python main.py"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14.3-alpine3.15
    env_file:
      - .env
    healthcheck:
      test: sh -c "pg_isready -U swapi -d swapi"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    restart: unless-stopped

  pg_admin:
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    ports:
      - "5051:80"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 2G
